### ISSUE TITLE
dependency not found

### ISSUE THREAD

**Issue by fpguy** [darkfrog26/hyperscala#14]
Using the giter8 template, after sbt reStart i get this:

.
[info] Resolving org.scala-lang#scala-library;2.11.5 ...

M[info] Resolving org.hyperscala#hyperscala-ui_2.11;0.9.3 ...

M[info] Resolving org.hyperscala#hyperscala-web_2.11;0.9.3 ...

M[info] Resolving org.hyperscala#hyperscala-html_2.11;0.9.3 ...

M[info] Resolving org.hyperscala#hyperscala-core_2.11;0.9.3 ...

M[info] Resolving org.powerscala#powerscala-reflect_2.11;1.6.7 ...

M[info] Resolving org.ow2.asm#asm-all;5.0.3 ...

M[info] Resolving io.argonaut#argonaut_2.11;6.0.4 ...

M[info] Resolving org.scalaz#scalaz-core_2.11;7.0.6 ...

M[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.11;1.0.1 ...

M[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.1 ...

M[info] Resolving org.reflections#reflections;0.9.9 ...

M[info] Resolving com.google.guava#guava;15.0 ...

M[info] Resolving org.javassist#javassist;3.18.2-GA ...

M[info] Resolving com.google.code.findbugs#annotations;2.0.1 ...

M[info] Resolving org.scala-lang#scala-reflect;2.11.4 ...

M[info] Resolving org.powerscala#powerscala-hierarchy_2.11;1.6.7 ...

M[info] Resolving org.powerscala#powerscala-core_2.11;1.6.7 ...

M[info] Resolving com.typesafe.akka#akka-actor_2.11;2.3.6 ...

M[info] Resolving com.typesafe#config;1.2.1 ...

M[info] Resolving org.powerscala#powerscala-event_2.11;1.6.7 ...

M[info] Resolving org.powerscala#powerscala-concurrent_2.11;1.6.7 ...

M[info] Resolving org.powerscala#powerscala-property_2.11;1.6.7 ...

M[info] Resolving org.powerscala#powerscala-log_2.11;1.6.7 ...

M[info] Resolving org.jdom#jdom2;2.0.5 ...

M[info] Resolving jaxen#jaxen;1.1.6 ...

M[info] Resolving net.sourceforge.htmlcleaner#htmlcleaner;2.10 ...

M[info] Resolving org.json4s#muster-codec-jawn_2.11;0.3.0 ...

M[info] Resolving org.json4s#muster-core_2.11;0.3.0 ...

M[info] Resolving org.json4s#muster-codec-json_2.11;0.3.0 ...

M[info] Resolving org.jsawn#jawn-parser_2.11;0.5.4 ...

M[info] Resolving org.jsawn#jawn-parser_2.11;0.5.4 ...
[warn] 	module not found: org.jsawn#jawn-parser_2.11;0.5.4
[warn] ==== local: tried
[warn]   C:\Users\xxx\.ivy2\local\org.jsawn\jawn-parser_2.11\0.5.4\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/jsawn/jawn-parser_2.11/0.5.4/jawn-parser_2.11-0.5.4.pom
[info] Resolving org.json4s#muster-codec-jackson_2.11;0.3.0 ...

M[info] Resolving com.fasterxml.jackson.core#jackson-core;2.4.1.1 ...

M[info] Resolving com.fasterxml.jackson.core#jackson-databind;2.4.1.3 ...

M[info] Resolving com.fasterxml.jackson.core#jackson-annotations;2.4.0 ...

M[info] Resolving com.outr.net#outrnet-core_2.11;1.1.3 ...

M[info] Resolving javax.servlet#javax.servlet-api;3.1.0 ...

M[info] Resolving commons-fileupload#commons-fileupload;1.3.1 ...

M[info] Resolving commons-io#commons-io;2.2 ...

M[info] Resolving org.apache.httpcomponents#httpclient;4.3.5 ...

M[info] Resolving org.apache.httpcomponents#httpcore;4.3.2 ...

M[info] Resolving commons-logging#commons-logging;1.1.3 ...

M[info] Resolving commons-codec#commons-codec;1.6 ...

M[info] Resolving org.hyperscala#hyperscala-javascript_2.11;0.9.3 ...

M[info] Resolving org.hyperscala#hyperscala-svg_2.11;0.9.3 ...

M[info] Resolving net.sf.uadetector#uadetector-resources;2014.09 ...

M[info] Resolving net.sf.uadetector#uadetector-core;0.9.21 ...

M[info] Resolving net.sf.qualitycheck#quality-check;1.3 ...

M[info] Resolving com.google.code.findbugs#jsr305;2.0.3 ...

M[info] Resolving javax.annotation#jsr250-api;1.0 ...

M[info] Resolving org.slf4j#slf4j-api;1.7.7 ...

M[info] Resolving org.scala-lang.modules#scala-swing_2.11;1.0.1 ...

M[info] Resolving commons-codec#commons-codec;1.9 ...

M[info] Resolving org.hyperscala#hyperscala-realtime_2.11;0.9.3 ...

M[info] Resolving org.hyperscala#hyperscala-jquery_2.11;0.9.3 ...

M[info] Resolving org.hyperscala#hyperscala-connect_2.11;0.9.3 ...

M[info] Resolving com.outr.net#outrnet-jetty_2.11;1.1.3 ...

M[info] Resolving com.outr.net#outrnet-servlet_2.11;1.1.3 ...

M[info] Resolving org.eclipse.jetty#jetty-server;9.2.5.v20141112 ...

M[info] Resolving org.eclipse.jetty#jetty-http;9.2.5.v20141112 ...

M[info] Resolving org.eclipse.jetty#jetty-util;9.2.5.v20141112 ...

M[info] Resolving org.eclipse.jetty#jetty-io;9.2.5.v20141112 ...

M[info] Resolving org.scala-lang#scala-compiler;2.11.5 ...

M[info] Resolving org.scala-lang#scala-reflect;2.11.5 ...

M[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.3 ...

M[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.11;1.0.3 ...

M[info] Resolving jline#jline;2.12 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.jsawn#jawn-parser_2.11;0.5.4: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.jsawn:jawn-parser_2.11:0.5.4
[warn] 		  +- org.json4s:muster-codec-jawn_2.11:0.3.0
[warn] 		  +- org.hyperscala:hyperscala-core_2.11:0.9.3
[warn] 		  +- org.hyperscala:hyperscala-html_2.11:0.9.3
[warn] 		  +- org.hyperscala:hyperscala-svg_2.11:0.9.3
[warn] 		  +- org.hyperscala:hyperscala-web_2.11:0.9.3
[warn] 		  +- org.hyperscala:hyperscala-jquery_2.11:0.9.3
[warn] 		  +- org.hyperscala:hyperscala-connect_2.11:0.9.3
[warn] 		  +- org.hyperscala:hyperscala-realtime_2.11:0.9.3
[warn] 		  +- org.hyperscala:hyperscala-ui_2.11:0.9.3 (F:\Projects\temp\hypertest\build.sbt#L13-14)
[warn] 		  +- com.home:hypertest_2.11:0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: org.jsawn#jawn-parser_2.11;0.5.4: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:243)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:158)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:124)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
	at sbt.IvySbt$$anon$3.call(Ivy.scala:64)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
	at sbt.IvySbt.withIvy(Ivy.scala:119)
	at sbt.IvySbt.withIvy(Ivy.scala:116)
	at sbt.IvySbt$Module.withModule(Ivy.scala:147)
	at sbt.IvyActions$.updateEither(IvyActions.scala:156)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1282)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1279)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$84.apply(Defaults.scala:1309)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$84.apply(Defaults.scala:1307)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1312)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1306)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1324)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1264)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1242)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.jsawn#jawn-parser_2.11;0.5.4: not found
[error] Total time: 2 s, completed

**Comment by darkfrog26** [comment]
Which giter8 template did you use?

**Comment by fpguy** [comment]
did "g8 darkfrog26/hyperscala.g8" as recommened

**Comment by darkfrog26** [comment]
I just tested it myself and had no trouble.  Can you make sure you're using the latest version of SBT (0.13.7) and if it still isn't working let me know what OS you are running on.

**Comment by fpguy** [comment]
I added build.properties to enforce 0.13.7, nothing changed. I am on windows.

http://mvnrepository.com/artifact/org.spire-math/jawn-parser_2.11

there is no jawn-parser 0.5.4, from where is dependency coming from?

**Comment by fpguy** [comment]
can be fixed with: 
resolvers += "Jcenter" at "http://jcenter.bintray.com/"

**Comment by darkfrog26** [comment]
I honestly have no idea where that dependency is coming from.  Are you sure you don't have an SBT plugin specified or something that is bringing that over?  If you can figure out where that's coming from let me know and I'll get it resolved.  Unfortunately I'm unable to reproduce it though.

**Comment by hrj** [comment]
@fpguy You can find where the dependency comes from with [this plugin](https://github.com/jrudolph/sbt-dependency-graph).

**Comment by darkfrog26** [comment]
@fpguy were you ever able to get that resolved?
